<a href="https://colab.research.google.com/github/Savitanna/sberbank_data_analysis_06_07_21/blob/master/hw_2_numpy_Savitskaya_AV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [128]:
import pandas as pd
import numpy as np

### Упражнение 1

На одном графике изобразите время затраченное на вычисление с использованием массивов numpy и стандартных списков в питоне.  
Для более точных результатов замеряйте время выполнения функции несколько раз и усредняйте. 
* Используйте функцию `z = 2*x**2 + 4*y`
* Перемножение матриц размера n на n

### Упражнение 2
* Создайте массив чисел от 2 до 75. Выведите только нечётные. 
* Присвойте нечётным числам этого массива значение -1.



In [37]:
a = np.arange(2, 75+1, 1)
b=list(filter(lambda x: x % 2 != 0, a))
print('a = {}\nb = {}'.format(a, b))

a = [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75]
b = [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75]


In [38]:
c=a[np.where(a % 2 != 0)]
c
a[np.where(a % 2 != 0)]=-1
print('c = {}\na = {}'.format(c, a))

c = [ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53 55 57 59 61 63 65 67 69 71 73 75]
a = [ 2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1 24 -1
 26 -1 28 -1 30 -1 32 -1 34 -1 36 -1 38 -1 40 -1 42 -1 44 -1 46 -1 48 -1
 50 -1 52 -1 54 -1 56 -1 58 -1 60 -1 62 -1 64 -1 66 -1 68 -1 70 -1 72 -1
 74 -1]


### Упражнение 3

* Найдите в документации функцию, которая удаляет из одного массива элементы, которые есть в другом. 
* Приведите примеры использования.

### Упражнение 4

* Создайте случайную квадратную матрицу случайного размера от 10 до 100. 
* Найдите максимум и сумму элементов.
* Поделите каждый элемент матрицы на максимум.
* Отнимите от каждой строки матрицы среднее по строке.
* Замените максимальное значение на -1.

In [41]:
size_m1=10
size_m2=100
size_matrix=np.random.randint(size_m1, size_m2+1)
z1=np.random.random((size_matrix,size_matrix))
z1

array([[0.51795504, 0.69490676, 0.8225551 , ..., 0.4962851 , 0.66018848,
        0.52058344],
       [0.31648867, 0.13308136, 0.87333896, ..., 0.21371502, 0.76313134,
        0.17846122],
       [0.65448889, 0.67551046, 0.47970325, ..., 0.12054742, 0.10439498,
        0.20275478],
       ...,
       [0.66360872, 0.17860604, 0.81580143, ..., 0.72461378, 0.91494919,
        0.95157776],
       [0.8667537 , 0.06794839, 0.63302293, ..., 0.23454715, 0.57238345,
        0.84519559],
       [0.72611181, 0.79066046, 0.07777627, ..., 0.24792658, 0.00571732,
        0.11930753]])

In [42]:
z1_max=z1.max()
z1_mean=z1.sum()
print('z1_max = {}\nz1_mean = {}'.format(z1_max, z1_mean))

z1_max = 0.9998728727723023
z1_mean = 4000.1246224983834


In [43]:
z2=z1/z1_max
z2

array([[0.5180209 , 0.69499511, 0.82265969, ..., 0.4963482 , 0.66027241,
        0.52064963],
       [0.31652891, 0.13309828, 0.87345   , ..., 0.21374219, 0.76322837,
        0.17848391],
       [0.65457211, 0.67559635, 0.47976424, ..., 0.12056274, 0.10440825,
        0.20278056],
       ...,
       [0.6636931 , 0.17862875, 0.81590515, ..., 0.72470591, 0.91506552,
        0.95169875],
       [0.8668639 , 0.06795703, 0.63310341, ..., 0.23457697, 0.57245622,
        0.84530305],
       [0.72620413, 0.79076099, 0.07778616, ..., 0.2479581 , 0.00571805,
        0.1193227 ]])

In [44]:
z3_sum_row=z2.sum(axis=1)
z3_sum_row

array([45.18895096, 45.41578085, 47.972866  , 38.38362983, 51.81205139,
       47.17609642, 44.45330453, 43.80485441, 40.2891411 , 43.69994388,
       40.01254001, 47.2242275 , 47.95540494, 48.988073  , 50.58031374,
       48.97661853, 48.84780478, 48.49928308, 42.67088657, 38.10764404,
       48.30744638, 41.34775919, 47.35288907, 49.02086342, 39.72514595,
       44.99405679, 41.55429715, 47.7833822 , 46.60770887, 44.53251588,
       39.34589711, 48.01006415, 47.46055256, 45.02741399, 46.10988972,
       46.612466  , 44.96963935, 48.88462135, 43.57146469, 44.90040573,
       44.01997117, 45.26516611, 45.45088546, 48.58052784, 43.19332028,
       42.20129982, 44.24270491, 45.34466585, 44.20340355, 45.28242337,
       45.84774559, 40.07899402, 51.17729803, 43.40229371, 41.17543255,
       41.94996911, 45.11016626, 42.71153541, 48.614263  , 41.1151658 ,
       40.49693326, 46.67837963, 45.01179422, 46.06014291, 46.99391498,
       45.90608874, 43.58890249, 42.65158145, 44.04022032, 45.18

In [45]:
z4=z2-z3_sum_row
z4

array([[-44.67093006, -44.72078574, -47.15020631, ..., -43.05292915,
        -42.57684646, -45.61625128],
       [-44.87242205, -45.28268257, -47.099416  , ..., -43.33553515,
        -42.47389051, -45.958417  ],
       [-44.53437885, -44.7401845 , -47.49310176, ..., -43.4287146 ,
        -43.13271062, -45.93412035],
       ...,
       [-44.52525787, -45.2371521 , -47.15696085, ..., -42.82457143,
        -42.32205336, -45.18520216],
       [-44.32208706, -45.34782382, -47.33976259, ..., -43.31470037,
        -42.66466265, -45.29159786],
       [-44.46274683, -44.62501986, -47.89507984, ..., -43.30131925,
        -43.23140082, -46.01757821]])

In [46]:
z4_max_replace_ind=(z4==(z4.max()))
z4_max_replace_ind

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [47]:
z5=z4
z5[z5==(z5.max())]=-1
z5

array([[-44.67093006, -44.72078574, -47.15020631, ..., -43.05292915,
        -42.57684646, -45.61625128],
       [-44.87242205, -45.28268257, -47.099416  , ..., -43.33553515,
        -42.47389051, -45.958417  ],
       [-44.53437885, -44.7401845 , -47.49310176, ..., -43.4287146 ,
        -43.13271062, -45.93412035],
       ...,
       [-44.52525787, -45.2371521 , -47.15696085, ..., -42.82457143,
        -42.32205336, -45.18520216],
       [-44.32208706, -45.34782382, -47.33976259, ..., -43.31470037,
        -42.66466265, -45.29159786],
       [-44.46274683, -44.62501986, -47.89507984, ..., -43.30131925,
        -43.23140082, -46.01757821]])

### Упражнение 5
* Напишите функцию, которая берет многомерный вещественный массив с пропущенными значениями (np.nan) и возвращает его копию с заполненными пропусками (заменять средним значением всех элементов массива). Если в массиве одни пропущенные значения, заполните их нулями.

In [55]:
# создадим матрицу, где есть NaN
z5_1=np.random.randint(38,100,(3,4,8))*1.00
#z5_1
z5_2=z5_1
z5_2[z5_2%5==0]='NaN'
z5_2

array([[[86., nan, 82., nan, 57., 51., 42., 73.],
        [41., 73., 92., 39., nan, 49., nan, 58.],
        [82., nan, 91., 59., 98., 48., 61., 66.],
        [73., 51., nan, nan, 63., 86., 82., nan]],

       [[58., nan, 77., 69., 51., 71., 98., 72.],
        [97., nan, 79., 78., 64., 69., 39., 62.],
        [nan, 72., 69., nan, nan, nan, 43., 92.],
        [83., 47., 88., nan, 72., 82., 42., 73.]],

       [[nan, nan, 46., 67., 64., 66., nan, 96.],
        [73., 97., 84., nan, 47., 96., 53., 93.],
        [58., 73., 67., 94., 44., 56., nan, 42.],
        [86., 48., 71., 39., 56., 57., nan, 51.]]])

In [56]:
# функция
def func_replace_NaN_mean(x):
    x_mean = round(np.nanmean(x),2)
    y_NaN=x
    y_NaN[np.where(np.isnan(y_NaN))] = x_mean
    return y_NaN

# вызов функции
z5_end=func_replace_NaN_mean(z5_2)
z5_end

array([[[86.  , 67.65, 82.  , 67.65, 57.  , 51.  , 42.  , 73.  ],
        [41.  , 73.  , 92.  , 39.  , 67.65, 49.  , 67.65, 58.  ],
        [82.  , 67.65, 91.  , 59.  , 98.  , 48.  , 61.  , 66.  ],
        [73.  , 51.  , 67.65, 67.65, 63.  , 86.  , 82.  , 67.65]],

       [[58.  , 67.65, 77.  , 69.  , 51.  , 71.  , 98.  , 72.  ],
        [97.  , 67.65, 79.  , 78.  , 64.  , 69.  , 39.  , 62.  ],
        [67.65, 72.  , 69.  , 67.65, 67.65, 67.65, 43.  , 92.  ],
        [83.  , 47.  , 88.  , 67.65, 72.  , 82.  , 42.  , 73.  ]],

       [[67.65, 67.65, 46.  , 67.  , 64.  , 66.  , 67.65, 96.  ],
        [73.  , 97.  , 84.  , 67.65, 47.  , 96.  , 53.  , 93.  ],
        [58.  , 73.  , 67.  , 94.  , 44.  , 56.  , 67.65, 42.  ],
        [86.  , 48.  , 71.  , 39.  , 56.  , 57.  , 67.65, 51.  ]]])

### Упражнение 6
* Напишите функцию которая нормализирует заданный numpy-массив, так чтобы его значения лежали в интервале $[0, 1]$.

In [64]:
# создадим матрицу
z6_1=np.random.randint(38,72,(3,4,8))*1.03
z6_1

array([[[56.65, 71.07, 40.17, 65.92, 41.2 , 56.65, 65.92, 39.14],
        [62.83, 73.13, 67.98, 62.83, 44.29, 55.62, 51.5 , 57.68],
        [42.23, 61.8 , 41.2 , 61.8 , 61.8 , 48.41, 62.83, 43.26],
        [62.83, 66.95, 48.41, 41.2 , 54.59, 44.29, 41.2 , 52.53]],

       [[56.65, 45.32, 43.26, 72.1 , 46.35, 41.2 , 69.01, 43.26],
        [60.77, 55.62, 63.86, 55.62, 52.53, 50.47, 55.62, 55.62],
        [52.53, 65.92, 40.17, 58.71, 53.56, 55.62, 45.32, 60.77],
        [72.1 , 40.17, 66.95, 52.53, 70.04, 73.13, 71.07, 52.53]],

       [[56.65, 57.68, 71.07, 46.35, 63.86, 41.2 , 50.47, 57.68],
        [61.8 , 45.32, 60.77, 69.01, 52.53, 64.89, 54.59, 49.44],
        [64.89, 70.04, 44.29, 48.41, 39.14, 51.5 , 69.01, 66.95],
        [47.38, 42.23, 61.8 , 39.14, 59.74, 51.5 , 67.98, 65.92]]])

In [68]:
# функция
def func_Normalization(x):
    x_min = round(np.min(x),2)
    x_max = round(np.max(x),2)
    y_Normal = np.round((x-x_min)/(x_max-x_min),3)
    return y_Normal

# вызов функции
z6_end=func_Normalization(z6_1)
z6_end

array([[[0.515, 0.939, 0.03 , 0.788, 0.061, 0.515, 0.788, 0.   ],
        [0.697, 1.   , 0.848, 0.697, 0.152, 0.485, 0.364, 0.545],
        [0.091, 0.667, 0.061, 0.667, 0.667, 0.273, 0.697, 0.121],
        [0.697, 0.818, 0.273, 0.061, 0.455, 0.152, 0.061, 0.394]],

       [[0.515, 0.182, 0.121, 0.97 , 0.212, 0.061, 0.879, 0.121],
        [0.636, 0.485, 0.727, 0.485, 0.394, 0.333, 0.485, 0.485],
        [0.394, 0.788, 0.03 , 0.576, 0.424, 0.485, 0.182, 0.636],
        [0.97 , 0.03 , 0.818, 0.394, 0.909, 1.   , 0.939, 0.394]],

       [[0.515, 0.545, 0.939, 0.212, 0.727, 0.061, 0.333, 0.545],
        [0.667, 0.182, 0.636, 0.879, 0.394, 0.758, 0.455, 0.303],
        [0.758, 0.909, 0.152, 0.273, 0.   , 0.364, 0.879, 0.818],
        [0.242, 0.091, 0.667, 0.   , 0.606, 0.364, 0.848, 0.788]]])

### Упражнение 7
* Запишите numpy-array в файл.
* Считайте numpy-array из файла.

In [65]:
size_m1_s=4
size_m2_s=8
size_matrix_s=np.random.randint(size_m1_s, size_m2_s+1)
z1_save=np.random.random((size_matrix_s,size_matrix_s))
z1_save

array([[0.19402479, 0.87538233, 0.06087767, 0.07825319, 0.43455463],
       [0.034233  , 0.89257809, 0.91136937, 0.87869544, 0.70251366],
       [0.50245725, 0.44248445, 0.28218675, 0.48698405, 0.49877198],
       [0.96132527, 0.49675326, 0.07396594, 0.46700615, 0.08675805],
       [0.20900616, 0.86399139, 0.44693181, 0.0796093 , 0.94236932]])

In [66]:
# запись в файл
np.save('example_save_arr_Savitskaya', z1_save)

In [67]:
# чтение из файла
z2_load=np.load('example_save_arr_Savitskaya.npy')
z2_load

array([[0.19402479, 0.87538233, 0.06087767, 0.07825319, 0.43455463],
       [0.034233  , 0.89257809, 0.91136937, 0.87869544, 0.70251366],
       [0.50245725, 0.44248445, 0.28218675, 0.48698405, 0.49877198],
       [0.96132527, 0.49675326, 0.07396594, 0.46700615, 0.08675805],
       [0.20900616, 0.86399139, 0.44693181, 0.0796093 , 0.94236932]])

### Упражнение 8
* Создайте случайный массив
* Найдите в массиве элемент ближайший к данному

In [105]:
# создаем случайный массив
size_m1=3
size_m2=5
z8_1=np.round(np.random.random((np.random.randint(size_m1, size_m2+1),np.random.randint(size_m1, size_m2+1))), 4)
z8_1

array([[0.2353, 0.6725, 0.3974, 0.4526],
       [0.6161, 0.3798, 0.2401, 0.4222],
       [0.259 , 0.1068, 0.229 , 0.0188]])

In [106]:
# генерируем случайное число, ближайшее к которому будем искать в массиве
z8_looking_for = np.round(np.random.uniform(0,1), 4)
z8_looking_for

0.1017

In [107]:
# ищем в массиве ближайший элемент
#z8_2=z8_1
index = np.where((np.abs(z8_1-z8_looking_for))==(np.abs(z8_1-z8_looking_for).min()))
index

(array([2]), array([1]))

In [108]:
print(z8_1[index])

[0.1068]


### Упражнение 9

* Напишите функцию, которая возвращает  $n \times m$ целочисленную матрицу с заданным значением на границах матрицы и с заданным значением внутри

In [112]:
# функция
def func_create_Matrix(M_n, M_m, V_ext, V_in):
    Matrix_create = np.ones((M_n,M_m), dtype=int)*V_ext
    Matrix_create[1:-1,1:-1]=V_in
    return Matrix_create

# вызов функции
z9_n=4
z9_m=7
z9_V_ext=8
z9_V_in=1
z9_end=func_create_Matrix(z9_n, z9_m, z9_V_ext, z9_V_in)
z9_end


array([[8, 8, 8, 8, 8, 8, 8],
       [8, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 8],
       [8, 8, 8, 8, 8, 8, 8]])

### Упражнение 10
* Напишите функцию, которая сортирует строки данной матрицы по значениям заданного столбца в порядке убывания. 

In [137]:
#создаем матрицу, которую будем сортировать
z10_1= np.random.randint(0, 1000, (3, 4))
z10_1

array([[997, 986, 540, 985],
       [796, 624, 919, 685],
       [ 99, 156, 771, 450]])

In [146]:
# функция
def func_Sort_Matrix(z_Sort, col_Sort):
    Matrix_Sort = z_Sort[z_Sort[:,col_Sort].argsort()][::-1]
    return Matrix_Sort

# устанавливаем столбец, по которому будем сортировать
z10_col = 2  

# вызов функции
z10_end=func_Sort_Matrix(z10_1, z10_col)
z10_end

array([[796, 624, 919, 685],
       [ 99, 156, 771, 450],
       [997, 986, 540, 985]])

### Упражнение 11

* Напишите функцию, которая создает двоичную матрицу шахматной доски с заданным shape

Пример 4x4:
```python
[[0, 1, 0, 1],
 [1, 0, 1, 0],
 [0, 1, 0, 1],
 [1, 0, 1, 0]]
```

In [149]:
# функция
def func_Creat_Matrix_1(M_r):
    Matrix_C = np.zeros((M_r,M_r), dtype=int)
    Matrix_C[1::2,::2] = 1
    Matrix_C[::2,1::2] = 1
    return Matrix_C

# исходные параметры
z11_m = 5  

# вызов функции
z11_end=func_Creat_Matrix_1(z11_m)
z11_end

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

### Упражнение 12
* Напишите игру [life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life), используя массивы numpy.
* Визуализируйте интерактивно ее результаты.



In [167]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1,1:-1]==0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100):
    print(Z)
    Z = iterate(Z)

[[0 1 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 1 1 0]
 ...
 [1 1 0 ... 0 1 1]
 [0 0 1 ... 1 1 1]
 [0 1 0 ... 0 0 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 1 ... 1 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 0 1 ... 1 1 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 1 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 1 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 1 ... 0 1 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [